### ISSUE TITLE
Warning: truncating very long token (%d characters) for NERsuite' % len(self.text), file=sys.stderr

### ISSUE THREAD

**Issue by Crucialer** [spyysalo/bc2gm-corpus#1]
when I use https://github.com/spyysalo/standoff2conll
with
mkdir conll
for s in train devel test; do
    standoff2conll.py -n standoff/$s > conll/$s.tsv; done
done
to converted the standoff into a CoNLL-like format, I encountered the following problem:
![image](https://user-images.githubusercontent.com/40562250/69313421-7066ad80-0c6c-11ea-8cd0-bfdbc531421d.png)
How can I solve the problem?

**Comment by Crucialer** [comment]
I get it now.
when I use the code ,I think these are some bugs:
==================================
![image](https://user-images.githubusercontent.com/40562250/69330286-9c465b00-0c8d-11ea-8336-03b069748879.png)
The right usage is :
=================
First, you need create a shell scripts by : 
----------------------------------------------
`touch stand0ff2conll.sh`

Then you write the following code in standoff2conll.sh
------------------------------------------------------
`mkdir conll`
`for s in train devel test; do`
   `python3  standoff2conll.py -n standoff/$s > conll/$s.tsv; `
`done.`

Finally,you run the standoff2conll.sh by : 
-----------------------------------------------
`sh standoff2conll.sh`

**Comment by zwd13122889** [comment]
I follow your right usage .But， i found some error.
AssertionError: text mismatch (check encoding?): 16-37
![image](https://user-images.githubusercontent.com/49578851/78262892-d2e18b80-7533-11ea-8cbd-5296dce43c79.png)
Can you  help me?

**Comment by zwd13122889** [comment]
I found a phenomenon.If the document doesn't have the label , it will  be written into the  .tsv.However, it will  report an error,like this :text mismatch.
